# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f00e6d989007f90f54bb92f775b19c0ccc5afd95f5e8ecfa7a5ef42da023c32bfffe2d55eedf651f20e64b5f1d1962246a4a6d2cbb4b9bc4e7e655ae5646332b

test:
  secret_key_base: 600a14f01c15499d751608829b5b689b95021921435a1ed80a9aacd7c1f4c9b55a2e78da5ddc47f263f39b4f49b7ea74f4332dc133d213911d671e7b73367033

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
